### 1. Criar transação de entrada
POST {{host}}/olympus/transaction HTTP/1.1
content-type: application/json
authorization: {{token}}

{
    "type": "income",
    "totalInCents": 2
}


### 2. Consultar saldo por id do Usuário
GET {{host}}/olympus/transaction/balance-by-customer HTTP/1.1
content-type: application/json
authorization: {{token}}